name = input("enter your name: ")
print("hello, " + name)
age = int(input("enter your age: "))
print("you are " + str(age) + " years old")
height = float(input("enter your height in cm: "))
print("your height is " + str(height) + " cm")
color = input("enter your favorite color: ")
print("your favorite color is " + color)
country = input("enter your country: ")
print("you are from " + country)
email = input("enter your email: ")
print("your email is " + email)